Update test.yml
Signed-off-by: laurentsimon <64505099+laurentsimon@users.noreply.github.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -7,13 +7,16 @@ jobs:
       - name: test
         run: |
           echo "GH_AUTH_TOKEN:"
-          gh auth login --with-token $(echo ${{ secrets.GH_AUTH_TOKEN }}) || echo "failed login"
+          export GH_TOKEN=${{ secrets.GH_AUTH_TOKEN }}
+          gh auth login || echo "failed login"
           gh auth status || echo "failed status"
           
           echo "PERSONAL_ACCESS_TOKEN:"
-          gh auth login --with-token $(echo ${{ secrets.PERSONAL_ACCESS_TOKEN }}) || echo "failed login"
+          export GH_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
+          gh auth login || echo "failed login"
           gh auth status || echo "failed status"
           
           echo "SCORECARD_TOKEN:"
-          gh auth login --with-token $(echo ${{ secrets.SCORECARD_TOKEN }}) || echo "failed login"
+          export GH_TOKEN=${{ secrets.SCORECARD_TOKEN }}
+          gh auth login || echo "failed login"
           gh auth status || echo "failed status"
